DROP DATABASE IF EXISTS tododb;
CREATE DATABASE IF NOT EXISTS tododb;
USE tododb;

DROP TABLE IF EXISTS todos;

CREATE TABLE IF NOT EXISTS todos
(
    id           INT          NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title        VARCHAR(255) NOT NULL,
    description  VARCHAR(255) NOT NULL,
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    is_completed TINYINT(1)
);