version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: tododb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build: .
    depends_on:
      - postgres
    environment:
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_HOST: host.docker.internal
      DB_PORT: 5432
      DB_NAME: tododb
      SERVER_PORT: 8080
      BASE_URL: http://localhost:8080
    ports:
      - "8080:8080"

volumes:
  postgres_data:
